### ISSUE TITLE
HTML templates no longer works in Thunderbird 115.3.1

### ISSUE THREAD

**Issue by dukethepenguin** [thundernest/quicktext#380]
Hi,
after upgrade to Thunderbird 115.3.1 with Quicktext 5.14 adding a html template no longer works as expected when using it to just add a signature. For plain text templates it works as expected.

However, for html it also works if the template is activated before writing anything else in the body, but if any text has been added first it does not work. The behavior differs a bit depending on what activation key is used. If TAB is used the focus i shifted away from the body (to nowhere) and the template is not added. If another key (as F4) is used nothing happens at all and focus stays in the body.

The workaround I found so far was modifying the template to instead of adding a signature only it adds the greeting, then the cursor with a [[CURSOR]] directive within a separate paragraph, and then the html signature at the end. So seems Thunderbird has changed something in the html editor that affects Quicktext html templates.

**Comment by EagleMan819** [comment]
Hi, I've had a similar issue.  We use Quicktext to add HTML signatures to our emails.   Following the TB115 upgrade this week I noticed that while the function still works for new emails it does not when replying, irrespective of whether the original email was received pre-post upgrade.  According to TB we are using QT 5.14 last updated 12/10/23.  When trying to add to a reply the only thing that happens is that the line in which the cursor is placed gets deleted.  I tried reaching out to Mozilla but they gave me the sloping shoulder treatment....  Any ideas?  Great product (before) :-)

**Comment by jobisoft** [comment]
As indicated in [another issue](https://github.com/jobisoft/quicktext/issues/378), this is a Thunderbird bug. It only happens if you have fonts (in your message or in your template).

The bug has been fixed in Daily (Thunderbird 120), but still needs a bit of time before it reaches Thunderbird 115:
https://bugzilla.mozilla.org/show_bug.cgi?id=1857788

**Comment by jobisoft** [comment]
>  I tried reaching out to Mozilla but they gave me the sloping shoulder treatment.... 

Where?

**Comment by EagleMan819** [comment]
Not sure if you can see the image of the response from Mozilla below?

![image](https://github.com/jobisoft/quicktext/assets/147811388/345e45aa-5b7d-4c0d-881f-a0902ba12029)

I've tried removing/reloading quicktext and have discovered the following;

If I reply and put the cursor at the end of the text the signature image is added.
If I place the cursor after my reply but ahead of the original message the line is deleted, no signature
If I copy and paste the signature I have to press CTRL-Insert TWICE for it to appear
Hope this helps

**Comment by jobisoft** [comment]
> Not sure if you can see the image of the response from Mozilla below?
> 
> ![image](https://user-images.githubusercontent.com/147811388/274864223-345e45aa-5b7d-4c0d-881f-a0902ba12029.png)
> 

That is in fact the correct response. The Thunderbird Team does not deal with add-on issues, and you were given a proper pointer on where to get help. Looks good to me.

I know this bug is getting in the way of our daily routines, but the Team reacted fast after the bug was discovered, and it will be fixed soon-ish.

**Comment by elendil72** [comment]
Hello,
after one of the last TB update  (115.3.3) all my templates and groups from QuickText (5.14) disappeared? I do not use special fonts. Any idea in which folder I might find the old datas? Or does a solution for this problem already exist?
Thanx

**Comment by gactech** [comment]
> The bug has been fixed in Daily (Thunderbird 120), but still needs a bit of time before it reaches Thunderbird 115: https://bugzilla.mozilla.org/show_bug.cgi?id=1857788

Kindly inform, how much time it takes for fix to reach Thunderbird 115?

**Comment by jobisoft** [comment]
The fix landed in Firefox 115.5. Should reach Thunderbird 115.5 as well.

**Comment by elendil72** [comment]
After updating to TB 115.4.1 my QuickText templates appeared again! Thanks for your replies. Cheers....

**Comment by Winter84** [comment]
I've just upgraded to TB 115.4.2, and I still have the behaviour reported by @EagleMan819 above.

**Comment by jobisoft** [comment]
> I've just upgraded to TB 115.4.2, and I still have the behaviour reported by @EagleMan819 above.

As stated in https://github.com/jobisoft/quicktext/issues/380#issuecomment-1783392177:
> The fix landed in Firefox 115.5. Should reach Thunderbird 115.5 as well.

**Comment by DTM54** [comment]
Just updated Thunderbird to 115.5. Issue persists. Maybe 115.6 will do it. I hope!

**Comment by Nionor** [comment]
115.5 didn't do anything for me either.
But as a workaround I have noticed that if I move up a few rows so it's not directly above the reply text and try to insert it usually works.

**Comment by DTM54** [comment]
Another workaround that I discovered: It works if you insert the signature right at the end of the text you typed in the reply. That is, don't hit _Enter_ at the end of your text and then try to insert the signature on a blank line. You can then go back and insert the line breaks before the beginning of the signature, but I just modified the signature script to include a couple of breaks before the text of the signature itself.

**Comment by jobisoft** [comment]
After more research, I learned that there is another bug, which has not been back-ported by the Firefox team. Requested back-port.

**Comment by jobisoft** [comment]
I think this has now been fixed in 115.6 or 115.6.1.

Can we close this?

**Comment by elendil72** [comment]
Yes, it works fine again. Thanks!
